#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from tempfile import gettempdir
from typing import Any, Iterable

ROOT_MARKERS = [
    ".git",
    "package.json",
    "pyproject.toml",
    "go.mod",
    "Cargo.toml",
    "pom.xml",
    "build.gradle",
]

EXCLUDED_DIRS = {
    ".git",
    ".idea",
    ".vscode",
    ".DS_Store",
    "node_modules",
    "dist",
    "build",
    "coverage",
    ".next",
    ".nuxt",
    ".output",
    "target",
    "out",
    "tmp",
    ".cache",
    "__pycache__",
}

TEXT_SUFFIXES = {
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".mjs",
    ".cjs",
    ".css",
    ".scss",
    ".less",
    ".json",
    ".md",
    ".mdx",
    ".yml",
    ".yaml",
    ".toml",
    ".ini",
    ".env",
    ".txt",
    ".py",
    ".go",
    ".rs",
    ".java",
    ".kt",
    ".sh",
    ".dockerfile",
}

GENERATED_SCAN_SUFFIXES = {
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".mjs",
    ".cjs",
    ".json",
    ".yml",
    ".yaml",
    ".toml",
    ".py",
    ".go",
    ".rs",
    ".java",
    ".kt",
    ".sh",
    ".dockerfile",
}

STACK_HINTS = [
    ("next", "Next.js"),
    ("nuxt", "Nuxt"),
    ("react", "React"),
    ("react-router", "React Router"),
    ("vue", "Vue"),
    ("svelte", "Svelte"),
    ("@angular/core", "Angular"),
    ("express", "Express"),
    ("koa", "Koa"),
    ("fastify", "Fastify"),
    ("nestjs", "NestJS"),
    ("typescript", "TypeScript"),
    ("tailwindcss", "Tailwind CSS"),
    ("antd", "Ant Design"),
    ("zustand", "Zustand"),
    ("redux", "Redux"),
    ("mobx", "MobX"),
    ("axios", "Axios"),
    ("i18next", "i18next"),
    ("vitest", "Vitest"),
    ("jest", "Jest"),
    ("playwright", "Playwright"),
    ("cypress", "Cypress"),
]

ENTRY_HINTS = [
    ("README.md", "仓库说明入口"),
    ("package.json", "Node.js 命令和依赖入口"),
    ("pyproject.toml", "Python 项目入口"),
    ("go.mod", "Go 项目入口"),
    ("Cargo.toml", "Rust 项目入口"),
    ("Makefile", "构建/自动化入口"),
    ("Dockerfile", "容器构建入口"),
    ("tsconfig.json", "TypeScript 编译配置"),
    ("vite.config.ts", "Vite 构建入口"),
    ("vite.config.js", "Vite 构建入口"),
    ("next.config.ts", "Next.js 构建配置"),
    ("next.config.js", "Next.js 构建配置"),
    ("next.config.mjs", "Next.js 构建配置"),
    ("app/layout.tsx", "App Router 根布局"),
    ("app/page.tsx", "App Router 首页"),
    ("app/[[...slug]]/page.tsx", "Catch-all 页面入口"),
    ("src/main.ts", "前端启动入口"),
    ("src/main.tsx", "前端启动入口"),
    ("src/index.ts", "前端入口"),
    ("src/index.tsx", "前端入口"),
    ("src/App.tsx", "应用组合入口"),
    ("src/router/index.ts", "路由组合入口"),
    ("src/router/index.tsx", "路由组合入口"),
    ("src/router.ts", "路由定义入口"),
    ("src/server.ts", "服务端启动入口"),
    ("main.py", "Python 主入口"),
    ("src/main.py", "Python 主入口"),
    ("cmd/main.go", "Go 主入口"),
]

MODULE_HINT_DIRS = [
    "src/modules",
    "src/features",
    "src/pages",
    "src/admin-pages",
    "src/domain",
    "src/api",
    "src/stores",
    "app",
    "backend",
    "services",
]

CONFIG_CANDIDATES = [
    "package.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "package-lock.json",
    "pnpm-workspace.yaml",
    "tsconfig.json",
    "tsconfig.base.json",
    "vite.config.ts",
    "vite.config.js",
    "next.config.ts",
    "next.config.js",
    "next.config.mjs",
    "nuxt.config.ts",
    "webpack.config.js",
    "tailwind.config.ts",
    "tailwind.config.js",
    "postcss.config.js",
    "postcss.config.mjs",
    "eslint.config.js",
    "eslint.config.mjs",
    ".eslintrc",
    ".eslintrc.js",
    ".prettierrc",
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    ".github/workflows",
]

ENV_FILE_PATTERNS = [
    ".env",
    ".env.local",
    ".env.development",
    ".env.production",
    ".env.test",
    ".env.example",
    ".env.sample",
]

AUTO_GENERATED_PATTERNS = [
    "auto-generated",
    "automatically generated",
    "do not edit manually",
    "generated by",
    "codegen",
]

IMPORT_RE = re.compile(
    r"(?:import\s+[^'\"]*?from\s+|import\s*\(|require\()\s*['\"]([^'\"]+)['\"]"
)
ENV_VAR_RE = re.compile(
    r"process\.env\.([A-Z0-9_]+)|"
    r"(?:os\.getenv|getenv)\(['\"]([A-Z0-9_]+)['\"]\)|"
    r"readonly\s+([A-Z0-9_]+)\??\s*:"
)
EXPORTED_FUNCTION_RE = re.compile(r"export\s+(?:async\s+)?function\s+([A-Za-z0-9_]+)")
STORE_ACTION_RE = re.compile(r"^\s{2}([A-Za-z0-9_]+):\s*(?:async\s*)?\(", re.MULTILINE)
PAGE_MODULE_ROUTE_RE = re.compile(r"'(/src/pages/[^']+)'")
DEFAULT_ROUTE_PATH_RE = re.compile(r"path:\s*['\"]([^'\"]+)['\"]")


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(read_text(path))


def safe_rel(root: Path, path: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return str(path)


def md_link(root: Path, output_path: Path, repo_path: str) -> str:
    target = root / repo_path
    rel = os.path.relpath(target, output_path.parent).replace(os.sep, "/")
    return f"[`{repo_path}`]({rel})"


def resolve_user_path(root: Path, raw_path: str) -> Path:
    candidate = Path(raw_path).expanduser()
    if candidate.is_absolute() or raw_path.startswith("~"):
        return candidate.resolve()
    return (root / raw_path).resolve()


def default_internal_artifacts_dir() -> Path:
    preferred = Path("~/tmp").expanduser()
    if preferred.exists() and preferred.is_dir():
        return preferred / "repo-newcomer-onboarding"
    return Path(gettempdir()) / "repo-newcomer-onboarding"


def derive_internal_artifact_paths(output_path: Path, base_dir: Path) -> dict[str, Path]:
    stem = output_path.stem or "developer-guide"
    return {
        "facts": base_dir / f"{stem}.facts.json",
        "review_prompt": base_dir / f"{stem}.review-prompt.md",
        "review_playbook": base_dir / f"{stem}.review-playbook.md",
    }


def shorten(text: str, limit: int = 220) -> str:
    normalized = re.sub(r"\s+", " ", text).strip()
    if len(normalized) <= limit:
        return normalized
    return normalized[: limit - 1].rstrip() + "…"


def find_repo_root(start: Path, explicit_root: str | None = None) -> Path:
    if explicit_root:
        root = Path(explicit_root).expanduser().resolve()
        if not root.exists():
            raise FileNotFoundError(f"repo root does not exist: {root}")
        return root

    current = start.resolve()
    for candidate in [current, *current.parents]:
        if any((candidate / marker).exists() for marker in ROOT_MARKERS):
            return candidate
    raise FileNotFoundError(f"cannot infer repository root from {start}")


def iter_repo_files(root: Path) -> Iterable[Path]:
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [
            name
            for name in dirnames
            if name not in EXCLUDED_DIRS and not name.startswith(".git")
        ]
        base = Path(dirpath)
        for filename in filenames:
            yield base / filename


def list_top_dirs(root: Path) -> list[Path]:
    result: list[Path] = []
    for child in sorted(root.iterdir(), key=lambda p: p.name.lower()):
        if not child.is_dir():
            continue
        if child.name in EXCLUDED_DIRS or child.name.startswith("."):
            continue
        result.append(child)
    return result


def count_source_files(path: Path) -> int:
    count = 0
    for file in path.rglob("*"):
        if not file.is_file():
            continue
        if any(part in EXCLUDED_DIRS for part in file.parts):
            continue
        if file.suffix.lower() in TEXT_SUFFIXES:
            count += 1
    return count


def summarize_readme(root: Path) -> str | None:
    readme_candidates = ["README.md", "README.MD", "readme.md"]
    for name in readme_candidates:
        path = root / name
        if not path.exists():
            continue
        text = read_text(path).strip()
        if not text:
            return None
        blocks = [block.strip() for block in re.split(r"\n\s*\n", text) if block.strip()]
        for block in blocks:
            lines = [line.strip() for line in block.splitlines() if line.strip()]
            if not lines:
                continue
            if all(
                line.startswith(("#", "![", "[![", "<img", "<!--"))
                or re.fullmatch(r"[-*_` ]+", line)
                for line in lines
            ):
                continue
            joined = " ".join(line for line in lines if not line.startswith("#"))
            if joined:
                return shorten(joined)
        return shorten(text)
    return None


def detect_package_manager(root: Path) -> str | None:
    package_json = root / "package.json"
    if package_json.exists():
        payload = read_json(package_json)
        package_manager = payload.get("packageManager")
        if package_manager:
            return str(package_manager)
    if (root / "pnpm-lock.yaml").exists():
        return "pnpm (lockfile detected)"
    if (root / "yarn.lock").exists():
        return "yarn (lockfile detected)"
    if (root / "package-lock.json").exists():
        return "npm (lockfile detected)"
    return None


def detect_runtime_requirements(root: Path) -> list[str]:
    requirements: list[str] = []

    package_json = root / "package.json"
    if package_json.exists():
        payload = read_json(package_json)
        engines = payload.get("engines")
        if isinstance(engines, dict):
            for key in sorted(engines):
                requirements.append(f"{key}: {engines[key]}")
        package_manager = payload.get("packageManager")
        if package_manager:
            requirements.append(f"packageManager: {package_manager}")

    for name in [".nvmrc", ".node-version", ".python-version", ".ruby-version"]:
        path = root / name
        if path.exists():
            content = read_text(path).strip()
            if content:
                requirements.append(f"{name}: {content}")

    env_files = [name for name in ENV_FILE_PATTERNS if (root / name).exists()]
    if env_files:
        requirements.append(f"环境文件: {', '.join(env_files)}")

    dockerfiles = sorted(safe_rel(root, path) for path in root.glob("docker/**/Dockerfile*"))
    if (root / "Dockerfile").exists():
        dockerfiles.insert(0, "Dockerfile")
    if dockerfiles:
        requirements.append(f"Docker: {', '.join(dockerfiles[:4])}")

    return requirements


def detect_stack(root: Path) -> list[str]:
    results: list[str] = []

    package_json = root / "package.json"
    if package_json.exists():
        payload = read_json(package_json)
        deps = {**payload.get("dependencies", {}), **payload.get("devDependencies", {})}
        js_stack = []
        for pkg, label in STACK_HINTS:
            if pkg in deps:
                js_stack.append(f"{label} ({deps[pkg]})")
        if js_stack:
            results.extend(js_stack)
        else:
            results.append("Node.js ecosystem (package.json present)")

    if (root / "pyproject.toml").exists() or (root / "requirements.txt").exists():
        results.append("Python ecosystem")
    if (root / "go.mod").exists():
        results.append("Go ecosystem")
    if (root / "Cargo.toml").exists():
        results.append("Rust ecosystem")
    if (root / "pom.xml").exists() or (root / "build.gradle").exists() or (root / "build.gradle.kts").exists():
        results.append("Java/JVM ecosystem")

    if not results:
        results.append("Stack not auto-detected; inspect build files manually")
    return results


def parse_commands(root: Path) -> list[dict[str, str]]:
    package_json = root / "package.json"
    if not package_json.exists():
        return []
    payload = read_json(package_json)
    scripts = payload.get("scripts", {})
    rows: list[dict[str, str]] = []
    for name in sorted(scripts.keys()):
        rows.append(
            {
                "name": name,
                "command": str(scripts[name]),
                "category": classify_command(name, str(scripts[name])),
            }
        )
    return rows


def classify_command(name: str, command: str) -> str:
    text = f"{name} {command}".lower()
    if any(token in text for token in ["dev", "serve", "watch"]):
        return "dev"
    if any(token in text for token in ["build", "bundle", "compile"]):
        return "build"
    if any(token in text for token in ["start", "preview", "run"]):
        return "start"
    if any(token in text for token in ["test", "vitest", "jest", "playwright", "cypress", "pytest"]):
        return "test"
    if any(token in text for token in ["lint", "eslint", "stylelint"]):
        return "lint"
    if any(token in text for token in ["typecheck", "tsc", "mypy", "pyright"]):
        return "typecheck"
    if any(token in text for token in ["generate", "codegen", "swagger", "openapi", "graphql", "prisma", "migration"]):
        return "generate"
    if any(token in text for token in ["release", "publish", "deploy"]):
        return "release"
    return "other"


def group_commands(commands: list[dict[str, str]]) -> dict[str, list[dict[str, str]]]:
    grouped: dict[str, list[dict[str, str]]] = {}
    for row in commands:
        grouped.setdefault(row["category"], []).append(row)
    return grouped


def find_generated_hints(commands: list[dict[str, str]]) -> list[str]:
    hints: list[str] = []
    for row in commands:
        if row["category"] == "generate":
            hints.append(f"`{row['name']}` -> `{row['command']}`")
    return hints


def scan_generated_files(root: Path, limit: int = 12) -> list[str]:
    hits: list[str] = []
    for file in iter_repo_files(root):
        if len(hits) >= limit:
            break
        rel = safe_rel(root, file)
        if "/skills/" in rel or rel.startswith(".codex/skills/"):
            continue
        if file.suffix.lower() not in GENERATED_SCAN_SUFFIXES:
            continue
        try:
            if file.stat().st_size > 256_000:
                continue
            head = "".join(read_text(file).splitlines(True)[:20]).lower()
        except OSError:
            continue
        if any(pattern in head for pattern in AUTO_GENERATED_PATTERNS):
            hits.append(rel)
    return hits


def find_existing_paths(root: Path, candidates: Iterable[str]) -> list[str]:
    return [path for path in candidates if (root / path).exists()]


def collect_skill_catalog(root: Path) -> list[dict[str, str]]:
    skills_dirs = [root / "skills", root / ".codex" / "skills"]
    rows: list[dict[str, str]] = []
    seen: set[str] = set()
    for skills_dir in skills_dirs:
        if not skills_dir.exists():
            continue
        for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
            rel = safe_rel(root, skill_md)
            if rel in seen:
                continue
            seen.add(rel)
            text = read_text(skill_md)
            frontmatter = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
            name = skill_md.parent.name
            description = ""
            if frontmatter:
                block = frontmatter.group(1)
                name_match = re.search(r"^name:\s*(.+)$", block, re.MULTILINE)
                desc_match = re.search(r"^description:\s*(.+)$", block, re.MULTILINE)
                if name_match:
                    name = name_match.group(1).strip()
                if desc_match:
                    description = desc_match.group(1).strip()
            rows.append({"name": name, "description": description, "path": rel})
    return rows


def top_dir_descriptions(root: Path) -> list[dict[str, Any]]:
    descriptions = {
        "app": "App 入口、路由壳或服务端页面",
        "src": "主要业务源码",
        "docs": "文档与设计说明",
        "scripts": "自动化脚本与辅助工具",
        "skills": "可复用的 Codex Skills",
        ".codex": "Codex 相关配置与本地技能目录",
        "tests": "测试代码",
        "config": "配置项与环境模板",
        "packages": "多包仓库子包",
        "services": "后端服务或微服务目录",
        "public": "静态资源目录",
        "docker": "容器与环境构建配置",
    }
    rows: list[dict[str, Any]] = []
    for directory in list_top_dirs(root):
        rel = safe_rel(root, directory)
        child_dirs = [
            item.name
            for item in sorted(directory.iterdir(), key=lambda p: p.name.lower())
            if item.is_dir() and item.name not in EXCLUDED_DIRS and not item.name.startswith(".")
        ][:4]
        rows.append(
            {
                "path": rel,
                "description": descriptions.get(directory.name, "建议补充该目录职责"),
                "file_count": count_source_files(directory),
                "child_dirs": child_dirs,
            }
        )
    return rows


def collect_config_files(root: Path) -> list[str]:
    rows: list[str] = []
    for candidate in CONFIG_CANDIDATES:
        path = root / candidate
        if path.exists():
            rows.append(candidate)
    return rows


def collect_env_var_keys(root: Path, limit: int = 24) -> list[str]:
    keys: set[str] = set()
    candidate_paths = [
        path for path in iter_repo_files(root)
        if path.suffix.lower() in TEXT_SUFFIXES
        and any(part in {"src", "app", "types"} for part in path.parts)
    ]
    for path in candidate_paths:
        try:
            text = read_text(path)
        except OSError:
            continue
        for match in ENV_VAR_RE.finditer(text):
            key = next((group for group in match.groups() if group), None)
            if key:
                keys.add(key)
        if len(keys) >= limit:
            break
    return sorted(keys)[:limit]


def collect_api_response_signals(root: Path) -> list[str]:
    rows: list[str] = []
    api_types = root / "types" / "api.d.ts"
    if api_types.exists():
        text = read_text(api_types)
        if "interface ResponseStructure" in text:
            rows.append("`types/api.d.ts` 定义了 `API.ResponseStructure<T>` 统一响应结构。")
        if "type ListResponse" in text:
            rows.append("`types/api.d.ts` 定义了 `API.ListResponse<T>` 列表响应结构。")
    request_file = root / "src" / "utils" / "request.ts"
    if request_file.exists():
        text = read_text(request_file)
        if "API.ResponseStructure" in text:
            rows.append("`src/utils/request.ts` 使用 `API.ResponseStructure<T>` 作为请求封装泛型入口。")
        if "handleBusinessError" in text:
            rows.append("`src/utils/request.ts` 包含统一业务错误处理逻辑。")
    return rows


def collect_api_surface_summary(root: Path, limit: int = 8) -> list[dict[str, Any]]:
    api_root = root / "src" / "api"
    if not api_root.exists():
        return []
    rows: list[dict[str, Any]] = []
    for path in sorted(api_root.rglob("*"), key=lambda p: safe_rel(root, p)):
        if not path.is_file():
            continue
        if path.suffix.lower() not in {".ts", ".tsx", ".js", ".jsx"}:
            continue
        text = read_text(path)
        functions = EXPORTED_FUNCTION_RE.findall(text)
        if not functions:
            continue
        rows.append(
            {
                "path": safe_rel(root, path),
                "exported_functions": functions[:6],
                "export_count": len(functions),
            }
        )
    rows.sort(key=lambda item: (-item["export_count"], item["path"]))
    return rows[:limit]


def collect_store_summaries(root: Path, limit: int = 8) -> list[dict[str, Any]]:
    stores_root = root / "src" / "stores"
    if not stores_root.exists():
        return []
    rows: list[dict[str, Any]] = []
    for path in sorted(stores_root.glob("*/index.ts*"), key=lambda p: safe_rel(root, p)):
        text = read_text(path)
        actions = STORE_ACTION_RE.findall(text)
        rows.append(
            {
                "path": safe_rel(root, path),
                "name": path.parent.name,
                "actions": actions[:6],
            }
        )
        if len(rows) >= limit:
            break
    return rows


def collect_route_mapping_signals(root: Path) -> list[str]:
    rows: list[str] = []
    page_modules = root / "src" / "router" / "pageModules.ts"
    if page_modules.exists():
        text = read_text(page_modules)
        module_routes = PAGE_MODULE_ROUTE_RE.findall(text)
        if module_routes:
            samples = ", ".join(module_routes[:4])
            rows.append(f"`src/router/pageModules.ts` 映射了约 {len(module_routes)} 个懒加载页面模块；示例：{samples}")
    default_route = root / "src" / "router" / "default.ts"
    if default_route.exists():
        text = read_text(default_route)
        route_paths = [
            path for path in DEFAULT_ROUTE_PATH_RE.findall(text)
            if path and path != "/"
        ]
        if route_paths:
            samples = ", ".join(route_paths[:6])
            rows.append(f"`src/router/default.ts` 提供默认路由/菜单样本；路径示例：{samples}")
    router_index = root / "src" / "router" / "index.tsx"
    if router_index.exists():
        text = read_text(router_index)
        if "createBrowserRouter" in text:
            rows.append("`src/router/index.tsx` 使用 `createBrowserRouter` 组合客户端路由。")
        if "pageModules" in text:
            rows.append("`src/router/index.tsx` 通过 `pageModules` 做页面懒加载映射。")
    return rows


def collect_entry_points(root: Path) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for rel, role in ENTRY_HINTS:
        if (root / rel).exists():
            rows.append({"path": rel, "role": role})
    return rows


def extract_import_targets(root: Path, rel_path: str, limit: int = 5) -> list[str]:
    path = root / rel_path
    if not path.exists() or not path.is_file():
        return []
    text = read_text(path)
    imports: list[str] = []
    for match in IMPORT_RE.finditer(text):
        target = match.group(1)
        if not target:
            continue
        imports.append(target)
        if len(imports) >= limit:
            break
    return imports


def collect_architecture_chain(root: Path) -> list[dict[str, Any]]:
    chain_candidates = [
        "app/layout.tsx",
        "app/page.tsx",
        "app/[[...slug]]/page.tsx",
        "src/entry/AdminClientApp.tsx",
        "src/main.tsx",
        "src/main.ts",
        "src/App.tsx",
        "src/router/index.tsx",
        "src/router/index.ts",
        "src/router/default.ts",
        "src/api/index.ts",
        "src/api/service.ts",
        "src/stores",
        "src/domain",
    ]
    rows: list[dict[str, Any]] = []
    for rel in find_existing_paths(root, chain_candidates):
        role = next((item["role"] for item in collect_entry_points(root) if item["path"] == rel), "")
        rows.append(
            {
                "path": rel,
                "role": role or infer_chain_role(rel),
                "imports": extract_import_targets(root, rel),
            }
        )
    return rows


def infer_chain_role(rel: str) -> str:
    lower = rel.lower()
    if "layout" in lower:
        return "布局或框架外壳"
    if "/page" in lower or lower.endswith("page.tsx"):
        return "页面入口"
    if "/router" in lower:
        return "路由组合层"
    if "/api/" in lower:
        return "数据访问层"
    if "/stores" in lower:
        return "状态层"
    if "/domain" in lower:
        return "领域类型层"
    if lower.endswith("app.tsx"):
        return "应用组合层"
    if lower.endswith("main.tsx") or lower.endswith("main.ts"):
        return "启动入口"
    return "架构信号文件"


def collect_data_layer_signals(root: Path) -> list[dict[str, Any]]:
    candidates = [
        "src/api",
        "src/services",
        "src/stores",
        "src/store",
        "src/domain",
        "src/models",
        "src/server",
        "prisma",
        "db",
        "database",
        "migrations",
        "supabase",
    ]
    rows: list[dict[str, Any]] = []
    for rel in candidates:
        path = root / rel
        if not path.exists():
            continue
        if path.is_dir():
            rows.append(
                {
                    "path": rel,
                    "kind": "directory",
                    "file_count": count_source_files(path),
                }
            )
        else:
            rows.append({"path": rel, "kind": "file", "file_count": 1})
    return rows


def collect_route_signals(root: Path) -> list[str]:
    signals: list[str] = []
    if (root / "app").exists():
        app_pages = len(list((root / "app").glob("**/page.*")))
        app_routes = len(list((root / "app").glob("**/route.*")))
        signals.append(f"`app/` 下检测到约 {app_pages} 个页面文件、{app_routes} 个 route handler")
    if (root / "pages").exists():
        pages_count = len(list((root / "pages").glob("**/*.*")))
        signals.append(f"`pages/` 目录存在，约 {pages_count} 个文件")
    for rel in ["src/router", "src/routes", "router", "routes"]:
        path = root / rel
        if path.exists():
            signals.append(f"检测到路由目录 {rel}")
    return signals


def collect_module_areas(root: Path, limit: int = 12) -> list[dict[str, Any]]:
    areas: list[dict[str, Any]] = []
    for rel in MODULE_HINT_DIRS:
        base = root / rel
        if not base.exists() or not base.is_dir():
            continue
        children = [
            item
            for item in sorted(base.iterdir(), key=lambda p: p.name.lower())
            if item.is_dir() and item.name not in EXCLUDED_DIRS and not item.name.startswith(".")
        ]
        if not children:
            areas.append(
                {
                    "path": rel,
                    "group": rel,
                    "file_count": count_source_files(base),
                    "samples": sample_files(root, base, limit=2),
                }
            )
            continue
        for child in children:
            areas.append(
                {
                    "path": safe_rel(root, child),
                    "group": rel,
                    "file_count": count_source_files(child),
                    "samples": sample_files(root, child, limit=2),
                }
            )
    areas = [area for area in areas if area["file_count"] > 0]
    areas.sort(key=lambda item: (-item["file_count"], item["path"]))
    return areas[:limit]


def sample_files(root: Path, base: Path, limit: int = 2) -> list[str]:
    rows: list[str] = []
    for file in sorted(base.rglob("*"), key=lambda p: safe_rel(root, p)):
        if not file.is_file():
            continue
        if file.suffix.lower() not in TEXT_SUFFIXES:
            continue
        rows.append(safe_rel(root, file))
        if len(rows) >= limit:
            break
    return rows


def recommended_reading(root: Path) -> list[str]:
    preferred = [
        "README.md",
        "package.json",
        "pyproject.toml",
        "go.mod",
        "Cargo.toml",
        "Makefile",
        "pnpm-workspace.yaml",
        "tsconfig.json",
        "next.config.ts",
        "next.config.js",
        "vite.config.ts",
        "app/layout.tsx",
        "app/[[...slug]]/page.tsx",
        "src/main.tsx",
        "src/main.ts",
        "src/App.tsx",
        "src/router/index.tsx",
        "src/router/index.ts",
        "src/api",
        "src/domain",
        "src/stores",
    ]
    return find_existing_paths(root, preferred)


def collect_test_signals(root: Path, commands: list[dict[str, str]]) -> list[str]:
    signals: list[str] = []
    test_commands = [row["name"] for row in commands if row["category"] == "test"]
    if test_commands:
        signals.append(f"脚本层有测试命令：{', '.join(test_commands)}")
    if (root / ".github" / "workflows").exists():
        workflow_files = sorted(
            safe_rel(root, path)
            for path in (root / ".github" / "workflows").glob("*")
            if path.is_file()
        )
        if workflow_files:
            signals.append(f"检测到 CI 工作流：{', '.join(workflow_files[:4])}")
    return signals


def infer_repo_shape(facts: dict[str, Any]) -> list[str]:
    inferences: list[str] = []

    entry_paths = {item["path"] for item in facts["entry_points"]}
    route_signals = facts["route_signals"]
    if "app/layout.tsx" in entry_paths and any("src/router" in item["path"] for item in facts["architecture_chain"]):
        inferences.append("推断：仓库可能采用“框架壳 + 客户端路由”或混合式入口结构。")
    if facts["generated_hints"] or facts["generated_files"]:
        inferences.append("推断：项目存在代码生成或索引生成步骤，新增页面/模块后可能需要先生成产物。")
    if not facts["test_signals"]:
        inferences.append("推断：未明显检测到自动化测试/CI 入口，质量保障可能主要依赖 lint、类型检查或人工联调。")
    if any("app/" in signal or "`app/`" in signal for signal in route_signals) and any(
        area["group"] in {"src/admin-pages", "src/pages"} for area in facts["module_areas"]
    ):
        inferences.append("推断：业务页面可能并不完全按框架默认路由目录组织，还需要结合路由映射或菜单配置理解页面落点。")

    return inferences


def unresolved(message: str = "未从仓库自动确认，需维护者补充。") -> str:
    return message


def find_command(facts: dict[str, Any], *categories: str) -> str | None:
    for category in categories:
        for row in facts["commands"]:
            if row["category"] == category:
                return row["name"]
    return None


def install_command(facts: dict[str, Any]) -> str:
    manager = facts.get("package_manager") or ""
    if "pnpm" in manager:
        return "pnpm install"
    if "yarn" in manager:
        return "yarn install"
    if "npm" in manager:
        return "npm install"
    if (Path(facts["repo_root"]) / "pyproject.toml").exists():
        return "python -m pip install -e ."
    return unresolved("未自动识别安装命令，请结合包管理器补充。")


def dev_command(facts: dict[str, Any]) -> str:
    row_name = find_command(facts, "dev", "start")
    if row_name:
        prefix = "pnpm" if "pnpm" in (facts.get("package_manager") or "") else ""
        return f"{prefix} {row_name}".strip()
    return unresolved("未自动识别开发启动命令。")


def build_command(facts: dict[str, Any]) -> str:
    row_name = find_command(facts, "build")
    if row_name:
        prefix = "pnpm" if "pnpm" in (facts.get("package_manager") or "") else ""
        return f"{prefix} {row_name}".strip()
    return unresolved("未自动识别构建命令。")


def test_command(facts: dict[str, Any]) -> str:
    row_name = find_command(facts, "test")
    if row_name:
        prefix = "pnpm" if "pnpm" in (facts.get("package_manager") or "") else ""
        return f"{prefix} {row_name}".strip()
    return unresolved("未检测到测试命令。")


def lint_command(facts: dict[str, Any]) -> str:
    row_name = find_command(facts, "lint")
    if row_name:
        prefix = "pnpm" if "pnpm" in (facts.get("package_manager") or "") else ""
        return f"{prefix} {row_name}".strip()
    return unresolved("未检测到 lint 命令。")


def derive_local_url(facts: dict[str, Any]) -> str | None:
    for row in facts["commands"]:
        if row["category"] != "dev":
            continue
        match = re.search(r"--port\s+(\d+)|-p\s+(\d+)|:(\d{4,5})", row["command"])
        if not match:
            continue
        port = next((group for group in match.groups() if group), None)
        if port:
            return f"http://localhost:{port}"
    if any("Next.js" in item for item in facts["stack"]):
        return "http://localhost:3000"
    return None


def derive_core_functions(facts: dict[str, Any]) -> list[str]:
    rows: list[str] = []
    for area in facts["module_areas"]:
        if area["group"] not in {"src/admin-pages", "src/pages", "src/features", "src/modules"}:
            continue
        rows.append(f"`{area['path']}` 相关业务")
        if len(rows) >= 6:
            break
    if rows:
        return rows
    return [unresolved("未从目录结构中提取到清晰的业务模块，请维护者补充核心功能。")]


def derive_use_cases(facts: dict[str, Any]) -> list[str]:
    paths = " ".join(area["path"] for area in facts["module_areas"]).lower()
    cases: list[str] = []
    if "admin" in paths or "sys-user" in paths:
        cases.append("后台管理 / 权限与菜单管理")
    if "content" in paths or "video" in paths or "operation" in paths:
        cases.append("内容运营 / 页面配置 / 可视化搭建")
    if any("Next.js" in item or "React" in item for item in facts["stack"]):
        cases.append("前端控制台 / 内部运营平台")
    return cases or [unresolved("未自动提取到稳定的使用场景，请维护者补充。")]


def derive_architecture_mode(facts: dict[str, Any]) -> str:
    if facts["inferences"]:
        return facts["inferences"][0].replace("推断：", "")
    if facts["architecture_chain"]:
        return "项目具备明显的入口 -> 路由 -> 数据/状态层分层结构。"
    return unresolved("未自动识别明确架构模式。")


def derive_architecture_diagram(facts: dict[str, Any]) -> list[str]:
    paths = {item["path"] for item in facts["architecture_chain"]}
    if {"app/layout.tsx", "app/[[...slug]]/page.tsx", "src/App.tsx", "src/router/index.tsx"} <= paths:
        return [
            "Browser",
            "↓",
            "Next App Router Shell",
            "↓",
            "Client App (`src/App.tsx`)",
            "↓",
            "Router / Layout",
            "↓",
            "Pages / API / Stores",
        ]
    if facts["architecture_chain"]:
        labels = [item["role"] for item in facts["architecture_chain"][:5]]
        rows: list[str] = []
        for index, label in enumerate(labels):
            rows.append(label)
            if index < len(labels) - 1:
                rows.append("↓")
        return rows
    return [unresolved("未自动识别到可可靠绘制的架构主链。")]


def derive_layer_rows(facts: dict[str, Any]) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    mapping = {
        "app/layout.tsx": "框架壳 / 根布局",
        "src/App.tsx": "应用组合层",
        "src/router/index.tsx": "路由层",
        "src/api": "API / 数据访问层",
        "src/stores": "状态管理层",
        "src/domain": "领域类型层",
        "src/server": "服务端辅助层",
    }
    for path, role in mapping.items():
        if any(item["path"] == path for item in facts["architecture_chain"]) or any(
            item["path"] == path for item in facts["data_layer_signals"]
        ):
            rows.append((path, role))
    return rows


def expert_review_checks() -> list[str]:
    return [
        "技术栈对应的工具链是否有明显遗漏，例如 lint、typecheck、测试、构建或代码生成步骤。",
        "架构模式与目录结构描述是否专业，是否把框架壳、路由、状态、API、业务页面的职责分清楚。",
        "所有结论是否都能区分为事实或推断，避免把猜测写成定论。",
        "快速开始、开发流程、构建发布、配置管理、测试指南是否缺少对新人最关键的动作指引。",
        "如果仓库存在生成文件、历史遗留入口或混合架构，是否已明确提示开发者注意。",
    ]


def detect_review_profiles(facts: dict[str, Any]) -> list[str]:
    profiles: list[str] = []
    stack_text = " ".join(facts.get("stack", [])).lower()

    if any(token in stack_text for token in ["next.js", "react", "typescript"]):
        profiles.append("node-frontend")
    if "react router" in stack_text:
        profiles.append("client-router")
    if "go ecosystem" in stack_text:
        profiles.append("go-service")
    if "python ecosystem" in stack_text:
        profiles.append("python-service")
    if "java/jvm ecosystem" in stack_text:
        profiles.append("java-service")
    if facts.get("generated_hints") or facts.get("generated_files"):
        profiles.append("generated-artifacts")
    if any("app/" in signal or "`app/`" in signal for signal in facts.get("route_signals", [])):
        profiles.append("framework-shell")

    seen: set[str] = set()
    ordered: list[str] = []
    for profile in profiles:
        if profile in seen:
            continue
        seen.add(profile)
        ordered.append(profile)
    return ordered


def stack_specific_review_checks(profiles: list[str]) -> list[str]:
    rules: dict[str, list[str]] = {
        "node-frontend": [
            "Node / TypeScript / React 项目要检查 `eslint`、`typescript/tsc`、测试命令、构建命令是否缺失或被误写。",
            "如果检测到 Next.js，同时又存在客户端路由目录，要明确说明是框架壳 + 客户端路由的组合，而不是简单写成“纯 Next 页面路由”。",
            "如果检测到 Tailwind、Ant Design、Zustand、Axios、i18next 等依赖，相关章节应反映这些工具在样式、状态、请求、国际化上的角色。",
        ],
        "client-router": [
            "如果仓库使用 React Router，要检查文档是否把路由入口、页面目录和菜单/映射机制讲清楚。",
            "如果文件路由与客户端路由并存，要指出开发者新增页面时到底应该修改哪一层。",
        ],
        "go-service": [
            "Go 项目要检查 `go test`、`gofmt`、`golangci-lint`、migration、`cmd/` 入口等是否遗漏。",
            "如果目录接近 `cmd/internal/pkg` 分层，要避免误写成前端式目录说明。",
        ],
        "python-service": [
            "Python 项目要检查依赖管理、格式化、lint、测试工具、入口脚本和配置文件是否遗漏。",
            "如果存在 `pyproject.toml`、`requirements.txt`、`alembic`、`manage.py` 等信号，要在 Quick Start 和数据库章节体现。",
        ],
        "java-service": [
            "Java/JVM 项目要检查构建工具（Maven/Gradle）、测试、代码规范、启动入口和分层目录是否被正确识别。",
        ],
        "generated-artifacts": [
            "如果仓库有 codegen 或自动索引，审稿时必须确认相关文件被标记为“不要手改”，并在 FAQ / 开发流程中给出提醒。",
        ],
        "framework-shell": [
            "如果仓库存在框架壳层（如 App Router）和业务页面目录分离，审稿时要强调真正的业务入口链，而不是只列框架默认入口。",
        ],
    }

    rows: list[str] = []
    for profile in profiles:
        rows.extend(rules.get(profile, []))
    return rows


def stack_output_contracts(profiles: list[str]) -> list[str]:
    contracts: dict[str, list[str]] = {
        "node-frontend": [
            "最终文档的 Quick Start 必须给出安装命令、开发启动命令、本地访问地址，以及是否需要先执行生成步骤。",
            "最终文档的技术栈、架构、API、状态管理章节应明确点出 React / TypeScript / Next.js / 请求层 / 状态层这些角色，而不是只列目录。",
        ],
        "client-router": [
            "最终文档必须明确说明路由来源：框架文件路由、客户端路由、菜单树、生成映射分别承担什么职责。",
            "最终文档必须回答“新增页面时应该修改哪个目录、哪个映射文件或哪个菜单来源”。",
        ],
        "go-service": [
            "最终文档必须优先说明 `cmd/` 入口、`internal/` 分层、构建测试命令和运行方式。",
        ],
        "python-service": [
            "最终文档必须优先说明依赖安装、环境隔离、启动入口、迁移和配置文件位置。",
        ],
        "java-service": [
            "最终文档必须优先说明构建工具、启动方式、测试方式和打包结果。",
        ],
        "generated-artifacts": [
            "最终文档必须在 Quick Start、开发流程、FAQ、贡献指南中至少一处明确提醒“生成文件不要手改”。",
        ],
        "framework-shell": [
            "最终文档的架构图和入口链必须区分框架壳入口与真实业务入口，避免把两者混为一谈。",
        ],
    }
    rows: list[str] = []
    for profile in profiles:
        rows.extend(contracts.get(profile, []))
    return rows


def build_review_prompt(root: Path, output_path: Path, facts: dict[str, Any]) -> str:
    invocation = facts["script_path_relative_to_repo"]
    lines: list[str] = []
    lines.append("你现在是 Step 2 的隐藏审稿人（资深架构师 / 资深维护者视角）。")
    lines.append("请审阅 Step 1 生成的项目开发指南草稿，并直接输出修正后的最终版文档。")
    lines.append("")
    lines.append("工作目标：")
    lines.append("- 不输出 review 意见列表")
    lines.append("- 不输出点评说明")
    lines.append("- 直接输出修正后的完整 Markdown")
    lines.append("- 保持 Developer Guide 的整体结构")
    lines.append("- 所有无法从仓库确认的内容必须明确标为“未从仓库自动确认，需维护者补充”或同义表达")
    lines.append("")
    lines.append("输入材料：")
    lines.append(f"- 草稿文档：{safe_rel(root, output_path)}")
    lines.append("- 结构化事实 JSON：若已提供，则与草稿一起阅读")
    lines.append(f"- 生成脚本：{invocation}")
    if facts.get("review_profiles"):
        lines.append(f"- 已识别的审稿画像：{', '.join(facts['review_profiles'])}")
    if facts.get("stack"):
        lines.append(f"- 已识别的技术栈：{'、'.join(facts['stack'])}")
    if facts.get("env_var_keys"):
        lines.append(f"- 环境变量键摘要：{', '.join(facts['env_var_keys'])}")
    if facts.get("route_mapping_signals"):
        lines.append("- 路由映射摘要：")
        for item in facts["route_mapping_signals"][:4]:
            lines.append(f"  - {item}")
    if facts.get("store_summaries"):
        lines.append("- 状态层摘要：")
        for item in facts["store_summaries"][:4]:
            action_part = ", ".join(item["actions"]) if item["actions"] else "未自动提取到显式 action"
            lines.append(f"  - {item['name']}: {action_part}")
    lines.append("")
    lines.append("必须检查的审稿项：")
    for item in facts["expert_review_checks"]:
        lines.append(f"- {item}")
    if facts.get("stack_specific_review_checks"):
        lines.append("")
        lines.append("按技术栈追加检查项：")
        for item in facts["stack_specific_review_checks"]:
            lines.append(f"- {item}")
    if facts.get("stack_output_contracts"):
        lines.append("")
        lines.append("最终输出合同（按画像追加）：")
        for item in facts["stack_output_contracts"]:
            lines.append(f"- {item}")
    lines.append("")
    lines.append("额外要求：")
    lines.append("- 如果技术栈暗示某些常见工具链，但仓库未配置，明确写“未检测到”，不要脑补。")
    lines.append("- 如果目录结构与架构术语不一致，优先修正术语，而不是硬套 DDD / MVC / 微服务等标签。")
    lines.append("- 如果仓库存在代码生成、自动索引、历史遗留入口、双路由体系、混合渲染等现象，要在文档中明确提醒开发者。")
    lines.append("- 优先让新人能在 30 分钟内理解项目，在 2 小时内把项目跑起来。")
    lines.append("")
    lines.append("输出规则：")
    lines.append("- 输出完整的最终版 Markdown")
    lines.append("- 不要保留“Step 1 草稿”之类措辞")
    lines.append("- 可以重写句子，但不要删除关键 section")
    lines.append("- “事实与推断”章节必须保留")
    lines.append("- 如果某一节证据不足，不要删节，直接写出“未从仓库自动确认，需维护者补充”。")
    lines.append("- 如果发现草稿中的工具链判断有误，直接改成仓库真实状态。")
    lines.append("- 如果发现架构术语不专业，直接替换为更准确的表述。")
    lines.append("")
    lines.append("如果草稿中已经正确，也仍然要输出一版润色后的最终文档。")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_review_playbook(
    root: Path,
    output_path: Path,
    facts_output_rel: str | None,
    review_prompt_output_rel: str | None,
    facts: dict[str, Any],
) -> str:
    lines: list[str] = []
    lines.append("# Step 2 Review Playbook")
    lines.append("")
    lines.append("## 推荐执行顺序")
    lines.append("")
    lines.append("1. 打开 Step 1 生成的开发指南草稿。")
    lines.append("2. 打开结构化 facts JSON。")
    lines.append("3. 打开 Step 2 审稿 prompt。")
    lines.append("4. 用审稿 prompt 驱动专家模式 reviewer。")
    lines.append("5. 直接输出最终版 Markdown，并替换草稿。")
    lines.append("")
    lines.append("## 输入文件")
    lines.append("")
    lines.append(f"- 草稿：`{safe_rel(root, output_path)}`")
    if facts_output_rel:
        lines.append(f"- Facts：`{facts_output_rel}`")
    if review_prompt_output_rel:
        lines.append(f"- 审稿 Prompt：`{review_prompt_output_rel}`")
    lines.append("")
    lines.append("## 推荐拼装方式")
    lines.append("")
    lines.append("```text")
    lines.append("System: 你是隐藏审稿人，负责把 Step 1 草稿改写为最终版开发指南。")
    lines.append("User: 请阅读以下三个输入：草稿、facts JSON、审稿 prompt。")
    lines.append("User: 只输出修正后的完整 Markdown。")
    lines.append("```")
    lines.append("")
    lines.append("## 当前仓库画像")
    lines.append("")
    if facts.get("review_profiles"):
        lines.append(f"- 审稿画像：{', '.join(facts['review_profiles'])}")
    if facts.get("stack_output_contracts"):
        lines.append("- 输出合同重点：")
        for item in facts["stack_output_contracts"]:
            lines.append(f"  - {item}")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_facts(root: Path, output_path: Path, script_path: Path) -> dict[str, Any]:
    commands = parse_commands(root)
    facts = {
        "repo_root": str(root),
        "script_path": str(script_path),
        "script_path_relative_to_repo": safe_rel(root, script_path),
        "readme_summary": summarize_readme(root),
        "stack": detect_stack(root),
        "package_manager": detect_package_manager(root),
        "runtime_requirements": detect_runtime_requirements(root),
        "commands": commands,
        "commands_by_category": group_commands(commands),
        "generated_hints": find_generated_hints(commands),
        "generated_files": scan_generated_files(root),
        "top_level_dirs": top_dir_descriptions(root),
        "config_files": collect_config_files(root),
        "entry_points": collect_entry_points(root),
        "architecture_chain": collect_architecture_chain(root),
        "route_signals": collect_route_signals(root),
        "data_layer_signals": collect_data_layer_signals(root),
        "module_areas": collect_module_areas(root),
        "reading_order": recommended_reading(root),
        "skill_catalog": collect_skill_catalog(root),
        "test_signals": collect_test_signals(root, commands),
        "env_var_keys": collect_env_var_keys(root),
        "api_response_signals": collect_api_response_signals(root),
        "api_surface_summary": collect_api_surface_summary(root),
        "store_summaries": collect_store_summaries(root),
        "route_mapping_signals": collect_route_mapping_signals(root),
        "output_path": str(output_path),
        "expert_review_checks": expert_review_checks(),
    }
    facts["inferences"] = infer_repo_shape(facts)
    facts["review_profiles"] = detect_review_profiles(facts)
    facts["stack_specific_review_checks"] = stack_specific_review_checks(facts["review_profiles"])
    facts["stack_output_contracts"] = stack_output_contracts(facts["review_profiles"])
    return facts


def build_document(root: Path, output_path: Path, facts: dict[str, Any]) -> str:
    lines: list[str] = []
    invocation = facts["script_path_relative_to_repo"]

    lines.append("# 项目开发指南（Developer Guide）")
    lines.append("")
    lines.append("本指南用于帮助新加入项目的开发者快速理解项目、快速运行项目并开始开发。")
    lines.append("")
    lines.append("- Step 1（Generation）：由脚本生成第一版事实草稿。")
    lines.append("- Step 2（Review）：基于文末“专家审稿检查项”做第二轮修正，输出最终版。")
    lines.append("")
    lines.append(
        f"> 本文档由 `{invocation}` 生成；其目标不是一次性写完全部业务知识，而是提供足够稳的事实层供后续人工或大模型审阅。"
    )
    lines.append("")

    lines.append("# 1. 项目概览（Project Overview）")
    lines.append("")
    lines.append("## 1.1 项目背景")
    lines.append("")
    if facts["readme_summary"]:
        lines.append(f"- 事实：README 摘要为：{facts['readme_summary']}")
    else:
        lines.append(f"- 事实：{unresolved('README 中未自动提取到清晰的项目背景描述。')}")
    lines.append(f"- 推断：{derive_architecture_mode(facts)}")
    lines.append("")

    lines.append("## 1.2 核心功能")
    lines.append("")
    for item in derive_core_functions(facts):
        lines.append(f"- {item}")
    lines.append("")

    lines.append("## 1.3 典型使用场景")
    lines.append("")
    for item in derive_use_cases(facts):
        lines.append(f"- {item}")
    lines.append("")

    lines.append("## 1.4 技术栈")
    lines.append("")
    lines.append(f"- 技术栈：{'、'.join(facts['stack'])}")
    if facts["package_manager"]:
        lines.append(f"- 包管理器：{facts['package_manager']}")
    if facts["runtime_requirements"]:
        lines.append("- 运行时 / 环境线索：")
        for item in facts["runtime_requirements"]:
            lines.append(f"  - {item}")
    lines.append("")

    lines.append("## 1.5 系统架构图")
    lines.append("")
    lines.append("```text")
    for row in derive_architecture_diagram(facts):
        lines.append(row)
    lines.append("```")
    lines.append("")

    lines.append("# 2. 快速开始（Quick Start）")
    lines.append("")
    lines.append("## 2.1 环境要求")
    lines.append("")
    if facts["runtime_requirements"] or facts["package_manager"]:
        if facts["package_manager"]:
            lines.append(f"- 包管理器：{facts['package_manager']}")
        if facts["runtime_requirements"]:
            for item in facts["runtime_requirements"]:
                lines.append(f"- {item}")
    else:
        lines.append(f"- {unresolved('未从仓库中自动确认运行时版本要求。')}")
    lines.append("")

    lines.append("## 2.2 获取项目")
    lines.append("")
    lines.append("```bash")
    lines.append("# 远端仓库地址需按团队实际地址补充")
    lines.append("git clone <your-repo-url>")
    lines.append(f"cd {root.name}")
    lines.append("```")
    lines.append("")

    lines.append("## 2.3 安装依赖")
    lines.append("")
    lines.append("```bash")
    lines.append(install_command(facts))
    lines.append("```")
    lines.append("")

    lines.append("## 2.4 启动服务")
    lines.append("")
    lines.append("```bash")
    lines.append(dev_command(facts))
    lines.append("```")
    if facts["generated_hints"]:
        lines.append("")
        lines.append("补充提示：")
        for item in facts["generated_hints"]:
            lines.append(f"- {item}")
    lines.append("")

    lines.append("## 2.5 验证服务")
    lines.append("")
    local_url = derive_local_url(facts)
    if local_url:
        lines.append(f"- 可优先尝试访问：`{local_url}`")
    else:
        lines.append(f"- {unresolved('未自动识别本地访问地址，请结合启动命令确认。')}")
    lines.append("")

    lines.append("# 3. 项目目录结构（Project Structure）")
    lines.append("")
    lines.append("```text")
    lines.append(root.name)
    for item in facts["top_level_dirs"]:
        comment = shorten(item["description"], 30)
        lines.append(f"├── {item['path']}    # {comment}")
    lines.append("```")
    lines.append("")
    lines.append("## 目录说明")
    lines.append("")
    lines.append("| 目录 | 说明 |")
    lines.append("| --- | --- |")
    for item in facts["top_level_dirs"]:
        detail = item["description"]
        if item["child_dirs"]:
            detail += f"；子目录示例：{', '.join(item['child_dirs'])}"
        lines.append(f"| `{item['path']}` | {detail} |")
    lines.append("")

    lines.append("# 4. 系统架构设计（Architecture）")
    lines.append("")
    lines.append("## 4.1 架构模式")
    lines.append("")
    lines.append(f"- {derive_architecture_mode(facts)}")
    lines.append("")

    lines.append("## 4.2 各层职责")
    lines.append("")
    lines.append("| 层/目录 | 职责 |")
    lines.append("| --- | --- |")
    layer_rows = derive_layer_rows(facts)
    if layer_rows:
        for path, role in layer_rows:
            lines.append(f"| {md_link(root, output_path, path)} | {role} |")
    else:
        lines.append(f"| - | {unresolved('未自动识别稳定分层。')} |")
    if facts["route_mapping_signals"]:
        lines.append("")
        lines.append("补充路由 / 映射线索：")
        for item in facts["route_mapping_signals"]:
            lines.append(f"- {item}")
    lines.append("")

    lines.append("## 4.3 设计原则")
    lines.append("")
    lines.append("- 事实：仓库包含明确的入口、路由、数据/状态层线索。")
    if facts["generated_hints"] or facts["generated_files"]:
        lines.append("- 事实：存在生成文件或索引生成步骤，开发时需注意不要直接手改生成产物。")
    lines.append("- 推断：项目倾向于通过目录分层和模块分区来降低耦合度。")
    lines.append("")

    lines.append("# 5. 本地开发流程（Development Workflow）")
    lines.append("")
    lines.append("## 5.1 创建功能分支")
    lines.append("")
    lines.append("```bash")
    lines.append("git checkout -b feature/your-change")
    lines.append("```")
    lines.append(f"- 推断：{unresolved('仓库中未自动确认正式分支策略，以上仅为通用建议。')}")
    lines.append("")

    lines.append("## 5.2 开发流程")
    lines.append("")
    lines.append("```text")
    lines.append("1. 阅读入口链和业务模块")
    lines.append("2. 如有代码生成，先执行生成命令")
    lines.append("3. 编写/修改代码")
    lines.append("4. 运行 lint / test / build")
    lines.append("5. 手动验证关键页面或接口")
    lines.append("6. 提交 PR 或交由 Review")
    lines.append("```")
    lines.append("")

    lines.append("## 5.3 分支策略")
    lines.append("")
    lines.append(f"- {unresolved('未从仓库内自动提取到正式分支策略（如 main/develop/feature/*）。')}")
    lines.append("")

    lines.append("# 6. 编码规范（Coding Standards）")
    lines.append("")
    lines.append("## 6.1 命名规范")
    lines.append("")
    if facts["skill_catalog"]:
        standards = next((item for item in facts["skill_catalog"] if "standards" in item["name"]), None)
        if standards:
            lines.append(f"- 建议优先阅读 {md_link(root, output_path, standards['path'])}，该 skill 很可能承载仓库级编码约定。")
        else:
            lines.append(f"- {unresolved('未自动识别明确的命名规范文档。')}")
    else:
        lines.append(f"- {unresolved('未自动识别明确的命名规范文档。')}")
    lines.append("")

    lines.append("## 6.2 代码规范")
    lines.append("")
    lines.append(f"- Lint：`{lint_command(facts)}`")
    if any(row["category"] == "typecheck" for row in facts["commands"]):
        lines.append("- Typecheck：已检测到独立 typecheck 命令。")
    else:
        lines.append("- Typecheck：未检测到独立 typecheck 命令。")
    if facts["config_files"]:
        lines.append("- 配置文件：")
        for rel in facts["config_files"][:8]:
            lines.append(f"  - {md_link(root, output_path, rel)}")
    lines.append("")

    lines.append("## 6.3 错误处理")
    lines.append("")
    if (root / "src" / "utils" / "request.ts").exists():
        lines.append(f"- 事实：{md_link(root, output_path, 'src/utils/request.ts')} 负责统一请求、鉴权头、状态码和错误提示处理。")
    else:
        lines.append(f"- {unresolved('未自动识别统一错误处理入口。')}")
    lines.append("")

    lines.append("## 6.4 日志规范")
    lines.append("")
    lines.append(f"- {unresolved('未从仓库中自动识别统一日志库或日志字段规范。')}")
    lines.append("")

    lines.append("# 7. 配置管理（Configuration）")
    lines.append("")
    lines.append("## 7.1 配置文件")
    lines.append("")
    if facts["config_files"]:
        for rel in facts["config_files"][:12]:
            lines.append(f"- {md_link(root, output_path, rel)}")
    else:
        lines.append(f"- {unresolved('未自动识别配置文件。')}")
    lines.append("")

    lines.append("## 7.2 环境变量")
    lines.append("")
    env_lines_written = False
    if facts["runtime_requirements"]:
        for item in facts["runtime_requirements"]:
            if "环境文件" in item:
                lines.append(f"- {item}")
                env_lines_written = True
    if facts["env_var_keys"]:
        lines.append(f"- 检测到的环境变量键：{', '.join(facts['env_var_keys'])}")
        env_lines_written = True
    if not env_lines_written:
        lines.append(f"- {unresolved('未自动识别环境文件或环境变量线索。')}")
    lines.append("")

    lines.append("## 7.3 Secrets 管理")
    lines.append("")
    lines.append(f"- {unresolved('仓库中未自动确认 Secrets 管理方案。')}")
    lines.append("")

    lines.append("# 8. 数据库设计（Database）")
    lines.append("")
    lines.append("## 8.1 Migration")
    lines.append("")
    migration_paths = [item["path"] for item in facts["data_layer_signals"] if item["path"] in {"prisma", "migrations", "db", "database"}]
    if migration_paths:
        for rel in migration_paths:
            lines.append(f"- 相关目录：{md_link(root, output_path, rel)}")
    else:
        lines.append(f"- {unresolved('未自动识别数据库 migration 目录或命令。')}")
    lines.append("")

    lines.append("## 8.2 表结构示例")
    lines.append("")
    lines.append(f"- {unresolved('未从仓库中自动提取到表结构定义或 ORM schema。')}")
    lines.append("")

    lines.append("# 9. API 设计规范（API Design）")
    lines.append("")
    lines.append("## 9.1 API Surface")
    lines.append("")
    api_paths = [item for item in facts["data_layer_signals"] if item["path"] in {"src/api", "src/server"}]
    if api_paths:
        for item in api_paths:
            lines.append(f"- {md_link(root, output_path, item['path'])}：约 {item['file_count']} 个相关文件")
    else:
        lines.append(f"- {unresolved('未自动识别 API 层目录。')}")
    if facts["api_surface_summary"]:
        lines.append("- 关键 API 文件摘要：")
        for item in facts["api_surface_summary"][:6]:
            lines.append(
                f"  - {md_link(root, output_path, item['path'])}：约 {item['export_count']} 个导出函数；示例：{', '.join(item['exported_functions'])}"
            )
    lines.append("")

    lines.append("## 9.2 返回格式")
    lines.append("")
    if facts["api_response_signals"]:
        for item in facts["api_response_signals"]:
            lines.append(f"- {item}")
        lines.append("- 推断：具体接口字段级 schema 仍需结合业务类型定义或后端文档进一步确认。")
    else:
        lines.append(f"- {unresolved('未自动识别统一返回格式。')}")
    lines.append("")

    lines.append("# 10. 日志与监控（Observability）")
    lines.append("")
    lines.append("## 10.1 日志")
    lines.append("")
    lines.append(f"- {unresolved('未自动识别日志框架。')}")
    lines.append("")
    lines.append("## 10.2 Metrics")
    lines.append("")
    lines.append(f"- {unresolved('未自动识别 metrics/监控配置。')}")
    lines.append("")
    lines.append("## 10.3 Tracing")
    lines.append("")
    lines.append(f"- {unresolved('未自动识别 tracing 配置。')}")
    lines.append("")

    lines.append("# 11. 测试指南（Testing）")
    lines.append("")
    lines.append("## 11.1 单元测试")
    lines.append("")
    lines.append(f"- 运行测试：`{test_command(facts)}`")
    lines.append("")
    lines.append("## 11.2 测试覆盖率")
    lines.append("")
    lines.append(f"- {unresolved('仓库中未自动确认覆盖率门槛。')}")
    lines.append("")
    lines.append("## 11.3 集成测试")
    lines.append("")
    if facts["test_signals"]:
        for item in facts["test_signals"]:
            lines.append(f"- {item}")
    else:
        lines.append(f"- {unresolved('未检测到集成测试或 CI 流程线索。')}")
    lines.append("")

    lines.append("# 12. 构建与发布（Build & Release）")
    lines.append("")
    lines.append("## 12.1 构建")
    lines.append("")
    lines.append(f"- 构建命令：`{build_command(facts)}`")
    lines.append("")
    lines.append("## 12.2 Docker 构建")
    lines.append("")
    docker_paths = [item["path"] for item in facts["top_level_dirs"] if item["path"] == "docker"]
    if docker_paths:
        lines.append(f"- 检测到 {md_link(root, output_path, 'docker')}，说明仓库存在容器构建/环境配置线索。")
    else:
        lines.append(f"- {unresolved('未自动识别 Docker 构建目录。')}")
    lines.append("")
    lines.append("## 12.3 CI/CD")
    lines.append("")
    if facts["test_signals"]:
        for item in facts["test_signals"]:
            if "CI 工作流" in item:
                lines.append(f"- {item}")
    else:
        lines.append(f"- {unresolved('未自动识别 CI/CD 工作流配置。')}")
    lines.append("")

    lines.append("# 13. 部署说明（Deployment）")
    lines.append("")
    lines.append(f"- {unresolved('仓库中未自动确认部署环境（dev/staging/prod）与部署方式。')}")
    lines.append("")

    lines.append("# 14. 常见问题（FAQ）")
    lines.append("")
    if facts["generated_hints"] or facts["generated_files"]:
        lines.append("- 新增页面或模块后未生效：先确认是否需要执行生成命令，避免遗漏索引更新。")
    if local_url:
        lines.append(f"- 本地服务无法访问：先确认开发服务是否已启动，并检查 `{local_url}` 或实际端口。")
    if (root / "src" / "utils" / "request.ts").exists():
        lines.append("- 出现登录态问题或 401：检查本地 token、请求头和统一请求封装逻辑。")
    if len(lines) >= 1 and lines[-1] == "":
        pass
    lines.append("")

    lines.append("# 15. 贡献指南（Contributing）")
    lines.append("")
    lines.append("- 建议提交前至少执行：")
    lines.append(f"  - `{lint_command(facts)}`")
    lines.append(f"  - `{test_command(facts)}`")
    lines.append(f"  - `{build_command(facts)}`")
    lines.append("- 若仓库有生成产物，提交前确认生成文件已同步更新。")
    lines.append(f"- 分支、PR、Commit 规范如未在仓库中声明，建议由团队另行补充。")
    lines.append("")

    lines.append("# 16. Roadmap")
    lines.append("")
    lines.append(f"- {unresolved('仓库中未自动识别公开的 roadmap / milestone 文档。')}")
    lines.append("")

    lines.append("# 17. 新人入门（Onboarding）")
    lines.append("")
    if facts["reading_order"]:
        lines.append("建议阅读顺序：")
        for idx, rel in enumerate(facts["reading_order"][:12], start=1):
            lines.append(f"- 第 {idx} 步：先读 {md_link(root, output_path, rel)}")
    else:
        lines.append(f"- {unresolved('未自动生成阅读顺序。')}")
    if facts["store_summaries"]:
        lines.append("- 关键状态管理摘要：")
        for item in facts["store_summaries"][:6]:
            action_part = ", ".join(item["actions"]) if item["actions"] else "未自动提取到显式 action"
            lines.append(
                f"  - {md_link(root, output_path, item['path'])}：store `{item['name']}`；动作示例：{action_part}"
            )
    if facts["skill_catalog"]:
        lines.append("- 仓库内技能目录：")
        for item in facts["skill_catalog"][:8]:
            desc = item["description"] if item["description"] else "(无描述)"
            lines.append(f"  - `{item['name']}`：{desc}，入口 {md_link(root, output_path, item['path'])}")
    lines.append("")

    lines.append("# 18. 事实与推断（Facts vs Inferences）")
    lines.append("")
    lines.append("- 事实：本指南中的路径、脚本、目录、配置和候选入口均来自当前仓库扫描结果。")
    if facts["inferences"]:
        for item in facts["inferences"]:
            lines.append(f"- {item}")
    else:
        lines.append("- 推断：暂未自动形成强信号，建议维护者补充业务流程与边界说明。")
    lines.append("")

    lines.append("# 19. 专家审稿检查项（Step 2 Review Rubric）")
    lines.append("")
    for item in facts["expert_review_checks"]:
        lines.append(f"- {item}")
    if facts["stack_specific_review_checks"]:
        lines.append("- 栈专属追加检查项：")
        for item in facts["stack_specific_review_checks"]:
            lines.append(f"  - {item}")
    if facts["stack_output_contracts"]:
        lines.append("- 最终输出合同：")
        for item in facts["stack_output_contracts"]:
            lines.append(f"  - {item}")
    lines.append("")

    lines.append("# 20. 再生成一次")
    lines.append("")
    lines.append(f"- 默认输出：`python3 {invocation}`")
    lines.append(f"- 只把最终稿写入 `docs/`，把中间产物写入临时目录：`python3 {invocation} --output docs/developer-guide.md --internal-artifacts-dir ~/tmp/repo-onboarding-run`")
    lines.append(f"- 指定仓库：`python3 {invocation} --repo-root /path/to/repo --output docs/developer-guide.md`")
    lines.append(f"- 显式导出结构化事实：`python3 {invocation} --facts-output docs/repo-facts.json`")
    lines.append(f"- 显式导出审稿 Prompt：`python3 {invocation} --facts-output docs/repo-facts.json --review-prompt-output docs/developer-guide-review-prompt.md`")
    lines.append(f"- 显式导出执行 Playbook：`python3 {invocation} --facts-output docs/repo-facts.json --review-prompt-output docs/developer-guide-review-prompt.md --review-playbook-output docs/developer-guide-review-playbook.md`")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate repository developer guides for newcomers.")
    parser.add_argument(
        "--output",
        default="docs/developer-guide.md",
        help="Output Markdown path, relative to repository root.",
    )
    parser.add_argument(
        "--facts-output",
        default=None,
        help="Optional JSON path, relative to repository root, for structured extracted facts.",
    )
    parser.add_argument(
        "--review-prompt-output",
        default=None,
        help="Optional Markdown/TXT path, relative to repository root, for the Step 2 expert-review prompt.",
    )
    parser.add_argument(
        "--review-playbook-output",
        default=None,
        help="Optional Markdown/TXT path, relative to repository root, for the Step 2 execution playbook.",
    )
    parser.add_argument(
        "--internal-artifacts-dir",
        default=None,
        help=(
            "Optional directory for hidden Step 2 support artifacts. "
            "Supports repo-relative paths, absolute paths, and ~/tmp style paths. "
            "When set, missing facts/review outputs are automatically written there."
        ),
    )
    parser.add_argument(
        "--repo-root",
        default=None,
        help="Optional repository root path. If omitted, auto-detect from script location.",
    )
    args = parser.parse_args()

    script_path = Path(__file__).resolve()
    root = find_repo_root(script_path.parent, args.repo_root)
    output_path = resolve_user_path(root, args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    internal_artifacts_dir: Path | None = None
    if args.internal_artifacts_dir:
        internal_artifacts_dir = resolve_user_path(root, args.internal_artifacts_dir)
    elif not any([args.facts_output, args.review_prompt_output, args.review_playbook_output]):
        internal_artifacts_dir = default_internal_artifacts_dir()

    auto_artifact_paths: dict[str, Path] = {}
    if internal_artifacts_dir:
        auto_artifact_paths = derive_internal_artifact_paths(output_path, internal_artifacts_dir)

    facts = build_facts(root, output_path, script_path)
    content = build_document(root, output_path, facts)
    output_path.write_text(content, encoding="utf-8")

    facts_target = args.facts_output
    if not facts_target and internal_artifacts_dir:
        facts_target = str(auto_artifact_paths["facts"])
    if facts_target:
        facts_path = resolve_user_path(root, facts_target)
        facts_path.parent.mkdir(parents=True, exist_ok=True)
        facts_path.write_text(
            json.dumps(facts, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        print(f"Wrote facts JSON to {facts_path}")

    review_prompt_target = args.review_prompt_output
    if not review_prompt_target and internal_artifacts_dir:
        review_prompt_target = str(auto_artifact_paths["review_prompt"])
    if review_prompt_target:
        review_prompt_path = resolve_user_path(root, review_prompt_target)
        review_prompt_path.parent.mkdir(parents=True, exist_ok=True)
        review_prompt_path.write_text(
            build_review_prompt(root, output_path, facts),
            encoding="utf-8",
        )
        print(f"Wrote review prompt to {review_prompt_path}")

    facts_output_rel = facts_target
    review_prompt_output_rel = review_prompt_target
    review_playbook_target = args.review_playbook_output
    if not review_playbook_target and internal_artifacts_dir:
        review_playbook_target = str(auto_artifact_paths["review_playbook"])
    if review_playbook_target:
        review_playbook_path = resolve_user_path(root, review_playbook_target)
        review_playbook_path.parent.mkdir(parents=True, exist_ok=True)
        review_playbook_path.write_text(
            build_review_playbook(
                root,
                output_path,
                facts_output_rel,
                review_prompt_output_rel,
                facts,
            ),
            encoding="utf-8",
        )
        print(f"Wrote review playbook to {review_playbook_path}")

    print(f"Wrote developer guide to {output_path}")


if __name__ == "__main__":
    main()
